### ISSUE TITLE
memory: No such file or directory error

### ISSUE THREAD

**Issue by aarobc** [luni64/staticFunctional#1]
Attempting to use with an atmega `MegaCoreX:megaavr:4809` and getting an error when attempting to compile:

```
arduino-cli compile --profile mega --build-path ./bin ./src/src.ino
In file included from /home/ac/code/demo/src/src.ino:4:0:
/home/ac/.arduino15/internal/staticFunctional_0.1.0_cb4f2dcb74fd18bc/staticFunctional/src/staticFunctional.h:15:10: fatal error: memory: No such file or directory
 #include <memory>
          ^~~~~~~~
compilation terminated.
```

This error also occurs via the arduino gui. 

It doesn't appear that this relies on any additional dependencies to download, and I'm not skilled enough with arduino to even start debugging this issue. Any guidance would be appreciated.

**Comment by luni64** [comment]
Sorry, this needs a toolchain supporting the standard libraries. Unfortunately the 8bit AVR  boards use a stripped down version of GCC which only supports a subset of the standard libraries.

**Comment by aarobc** [comment]
That is disappointing to hear. Thank you for clarifying.
